# Generated by Django 3.0.8 on 2020-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryapi',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
